# Generated by Django 4.0.10 on 2026-05-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entregador_nombre', models.CharField(max_length=255)),
                ('entregador_cedula', models.CharField(max_length=50)),
                ('entregador_empresa', models.CharField(max_length=255)),
                ('entregador_foto', models.TextField(blank=True, null=True)),
                ('entregador_firma', models.TextField(blank=True, null=True)),
                ('receptor_nombre', models.CharField(max_length=255)),
                ('receptor_firma', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(blank=True, null=True)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(blank=True, max_length=100, null=True)),
                ('disco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_disco', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('es_cambio', models.BooleanField(default=False)),
                ('cambio_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTAMIENTO', 'Alistamiento'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], default='RECIBIDO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('metadata_ocr', models.JSONField(blank=True, null=True)),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.recepcion')),
            ],
        ),
    ]
