# Generated by Django 5.2.13 on 2026-05-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='receptor_foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
