# Generated by Django 5.2.13 on 2026-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_puntoalistamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioitem',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTAMIENTO', 'Alistamiento'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolución'), ('DEVUELTO', 'Devuelto')], default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO', 'Técnico'), ('BODEGA', 'Personal de Bodega'), ('PROVEEDOR', 'Proveedor')], default='BODEGA', max_length=20),
        ),
    ]
