# Generated by Django 5.2.13 on 2026-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devolucion_inventarioitem_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO', 'Técnico'), ('BODEGA', 'Personal de Bodega'), ('PROVEEDOR', 'Proveedor'), ('PERSONALIZADO', 'Rol Personalizado')], default='BODEGA', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='api.permiso'),
        ),
    ]
