# Generated by Django 5.2.13 on 2026-05-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_permiso_alter_profile_role_profile_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='perfiles_extra', to='api.permiso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='BODEGA', max_length=50),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='api.permiso')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rol_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='api.rol'),
        ),
    ]
