# Generated by Django 5.2.13 on 2026-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_permisos_alter_profile_role_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='comentario_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
