# Generated by Django 5.2.13 on 2026-05-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inventarioitem_comentario_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='foto_alistador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='foto_entregador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='foto_receptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTAMIENTO', 'Alistamiento'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('PENDIENTE_DEVOLUCION', 'Pendiente Confirmación Proveedor'), ('DEVUELTO', 'Devuelto')], default='RECIBIDO', max_length=20),
        ),
        migrations.CreateModel(
            name='Alistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tecnico_nombre', models.CharField(max_length=255)),
                ('foto_tecnico', models.TextField(blank=True, null=True)),
                ('respuestas', models.JSONField(default=dict)),
                ('inventario_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alistamientos', to='api.inventarioitem')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
