# Generated by Django 5.2.13 on 2026-05-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_foto_fields_to_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='comentario_confirmacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
