# Generated by Django 5.2.13 on 2026-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_devolucion_comentario_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='requiere_alistamiento',
            field=models.BooleanField(default=True),
        ),
    ]
