# Generated by Django 5.2.13 on 2026-05-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alertacritica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='equipo_reemplazante_serial',
            field=models.CharField(blank=True, help_text='Serial of the new equipment replacing this one', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='fecha_inicio_reemplazo',
            field=models.DateTimeField(blank=True, help_text='Timestamp when replacement was registered', null=True),
        ),
    ]
