# Generated by Django 5.2.13 on 2026-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='item_unico',
            field=models.BooleanField(default=False),
        ),
    ]
