# Generated by Django 5.2.13 on 2026-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_procesador'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='responsable_devolucion',
            field=models.CharField(blank=True, help_text='Nombre de la persona que colocó el equipo en devolución', max_length=255, null=True),
        ),
    ]
