# Generated by Django 5.2.13 on 2026-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_inventarioitem_responsable_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='solicitante_cambio',
            field=models.CharField(blank=True, help_text='Nombre de la persona que solicitó el cambio', max_length=255, null=True),
        ),
    ]
