# Generated by Django 5.2.13 on 2026-06-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_inventarioitem_solicitante_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='documento_novedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='mensaje_novedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tiene_novedad',
            field=models.BooleanField(default=False),
        ),
    ]
