# Generated by Django 5.2.13 on 2026-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_devolucion_documento_novedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='equipo_asociado',
            field=models.IntegerField(blank=True, help_text='Item number del equipo al que está asociado', null=True),
        ),
    ]
