# Generated by Django 5.2.13 on 2026-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_inventarioitem_equipo_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='es_propio',
            field=models.BooleanField(default=False, help_text='Indica si el equipo es propio (no alquilado)'),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTAMIENTO', 'Alistamiento'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('EN_ESPERA_DEVOLUCION', 'En Espera de Devolución'), ('PENDIENTE_DEVOLUCION', 'Pendiente Confirmación Proveedor'), ('DEVUELTO', 'Devuelto'), ('ALMACENADO', 'Almacenado')], default='RECIBIDO', max_length=20),
        ),
    ]
