# Generated by Django 5.2.13 on 2026-07-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_profile_avatar_url_profile_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioitem',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALISTAMIENTO', 'Alistamiento'), ('DISPONIBLE', 'Disponible'), ('ENTREGADO', 'Entregado'), ('EN_ESPERA_DEVOLUCION', 'En Espera de Devolución'), ('PENDIENTE_DEVOLUCION', 'Pendiente Confirmación Proveedor'), ('DEVUELTO', 'Devuelto'), ('ALMACENADO', 'Almacenado'), ('DADO_DE_BAJA', 'Dado de Baja')], default='RECIBIDO', max_length=20),
        ),
    ]
