# Generated by Django 5.2.13 on 2026-07-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_inventarioitem_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el equipo fue dado de baja (confirmado por proveedor o manualmente)', null=True),
        ),
    ]
