# Generated by Django 5.2.13 on 2026-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_fecha_baja_to_inventarioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='aprobado_por_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='cedula_persona_devolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='firma_aprobador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='firma_persona_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='foto_persona_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='nombre_persona_devolucion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
