# Generated by Django 5.2.13 on 2026-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_devolucion_aprobado_por_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('CONFIRMADA', 'Confirmada')], default='PENDIENTE', max_length=20),
        ),
    ]
