# Generated by Django 5.2.13 on 2026-07-11 19:17

import django.db.models.deletion
from django.db import migrations, models

def populate_and_migrate_states(apps, schema_editor):
    EquipoEstado = apps.get_model('api', 'EquipoEstado')
    InventarioItem = apps.get_model('api', 'InventarioItem')

    STATUS_CHOICES = [
        ('RECIBIDO', 'Recibido'),
        ('ALISTAMIENTO', 'Alistamiento'),
        ('DISPONIBLE', 'Disponible'),
        ('ENTREGADO', 'Entregado'),
        ('EN_ESPERA_DEVOLUCION', 'En Espera de Devolución'),
        ('PENDIENTE_DEVOLUCION', 'Pendiente Confirmación Proveedor'),
        ('DEVUELTO', 'Devuelto'),
        ('ALMACENADO', 'Almacenado'),
        ('DADO_DE_BAJA', 'Dado de Baja'),
    ]

    state_objs = {}
    for code, label in STATUS_CHOICES:
        state_obj, _ = EquipoEstado.objects.get_or_create(nombre=code)
        state_objs[code] = state_obj

    recibido_state = state_objs.get('RECIBIDO')
    for item in InventarioItem.objects.all():
        old_estado = item.estado
        target_state = state_objs.get(old_estado, recibido_state)
        if target_state:
            item.estado_fk = target_state
            item.save(update_fields=['estado_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_proveedor_and_recepcion_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='estado_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_items_temp', to='api.equipoestado'),
        ),
        migrations.RunPython(populate_and_migrate_states, elidable=True),
    ]
