# Generated by Django 5.2.13 on 2026-07-11 19:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_equipoestado_inventarioitem_estado_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioitem',
            name='estado',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='estado_fk',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='estado',
            field=models.ForeignKey(default=api.models.get_default_estado, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_items', to='api.equipoestado'),
        ),
    ]
