# Generated by Django 5.2.13 on 2026-07-12 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_text_to_fk(apps, schema_editor):
    InventarioItem = apps.get_model('api', 'InventarioItem')
    TipoProducto = apps.get_model('api', 'TipoProducto')
    Marca = apps.get_model('api', 'Marca')
    Procesador = apps.get_model('api', 'Procesador')
    Disco = apps.get_model('api', 'Disco')
    TipoDisco = apps.get_model('api', 'TipoDisco')
    Ram = apps.get_model('api', 'Ram')
    Ubicacion = apps.get_model('api', 'Ubicacion')
    User = apps.get_model('auth', 'User')

    for item in InventarioItem.objects.all():
        if item.tipo_producto_old:
            tp, _ = TipoProducto.objects.get_or_create(nombre=item.tipo_producto_old.strip())
            item.tipo_producto = tp
        if item.marca_old:
            m, _ = Marca.objects.get_or_create(nombre=item.marca_old.strip())
            item.marca = m
        if item.procesador_old:
            p, _ = Procesador.objects.get_or_create(nombre=item.procesador_old.strip())
            item.procesador = p
        if item.disco_old:
            d, _ = Disco.objects.get_or_create(nombre=item.disco_old.strip())
            item.disco = d
        if item.tipo_disco_old:
            td, _ = TipoDisco.objects.get_or_create(nombre=item.tipo_disco_old.strip())
            item.tipo_disco = td
        if item.ram_old:
            r, _ = Ram.objects.get_or_create(nombre=item.ram_old.strip())
            item.ram = r
        if item.ubicacion_old:
            path_str = item.ubicacion_old.strip()
            parts = [p.strip() for p in path_str.split('>')]
            parent = None
            for part in parts:
                if part:
                    parent, _ = Ubicacion.objects.get_or_create(nombre=part, padre=parent)
            item.ubicacion = parent
        if item.responsable_devolucion_old:
            resp_str = item.responsable_devolucion_old.strip()
            user = User.objects.filter(username__iexact=resp_str).first()
            if not user:
                user = User.objects.filter(first_name__iexact=resp_str).first()
            if not user:
                safe_username = resp_str.replace(' ', '_').lower()[:150]
                user, _ = User.objects.get_or_create(username=safe_username, defaults={'first_name': resp_str})
            item.responsable_devolucion = user
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_recepcion_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='entregador',
            name='firma',
            field=models.TextField(blank=True, help_text='Firma en base64 (se actualiza en cada entrega)', null=True),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='foto',
            field=models.TextField(blank=True, help_text='Foto biométrica en base64 (se actualiza en cada entrega)', null=True),
        ),
        # 1. Rename old fields
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='tipo_producto',
            new_name='tipo_producto_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='marca',
            new_name='marca_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='procesador',
            new_name='procesador_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='disco',
            new_name='disco_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='tipo_disco',
            new_name='tipo_disco_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='ram',
            new_name='ram_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='ubicacion',
            new_name='ubicacion_old',
        ),
        migrations.RenameField(
            model_name='inventarioitem',
            old_name='responsable_devolucion',
            new_name='responsable_devolucion_old',
        ),

        # 2. Add new fields as ForeignKeys
        migrations.AddField(
            model_name='inventarioitem',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipoproducto'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.marca'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.procesador'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disco'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='tipo_disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipodisco'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ram'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ubicacion'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='responsable_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_responsables_devolucion', to=settings.AUTH_USER_MODEL),
        ),

        # 3. Run data migration
        migrations.RunPython(migrate_text_to_fk),

        # 4. Remove old fields
        migrations.RemoveField(
            model_name='inventarioitem',
            name='tipo_producto_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='marca_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='procesador_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='disco_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='tipo_disco_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='ram_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='ubicacion_old',
        ),
        migrations.RemoveField(
            model_name='inventarioitem',
            name='responsable_devolucion_old',
        ),
    ]
