# Generated by Django 5.2.13 on 2026-07-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_recepcion_proveedor_alter_entregador_firma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='entregador_firma',
            field=models.TextField(blank=True, help_text='Firma del entregador en esta entrega específica', null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='entregador_foto',
            field=models.TextField(blank=True, help_text='Foto biométrica del entregador en esta entrega específica', null=True),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='responsable_devolucion',
            field=models.ForeignKey(blank=True, help_text='Usuario que colocó el equipo en devolución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_responsables_devolucion', to=settings.AUTH_USER_MODEL),
        ),
    ]
