# Generated by Django 5.2.13 on 2026-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_recepcion_entregador_firma_recepcion_entregador_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del proveedor', max_length=50, null=True),
        ),
    ]
