# Generated by Django 5.2.13 on 2026-07-15 03:32

import django.db.models.deletion
from django.db import migrations, models


def associate_alistamientos_by_serial(apps, schema_editor):
    Alistamiento = apps.get_model('api', 'Alistamiento')
    InventarioItem = apps.get_model('api', 'InventarioItem')
    for alistamiento in Alistamiento.objects.filter(inventario_item__isnull=True):
        item = InventarioItem.objects.filter(serial=alistamiento.serial).first()
        if item:
            alistamiento.inventario_item = item
            alistamiento.save()
        else:
            alistamiento.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_proveedor_nit_proveedor_telefono'),
    ]

    operations = [
        migrations.RunPython(associate_alistamientos_by_serial, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alistamiento',
            name='serial',
        ),
        migrations.AlterField(
            model_name='alistamiento',
            name='inventario_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alistamientos', to='api.inventarioitem'),
        ),
    ]
