# Generated by Django 5.2.13 on 2026-07-15 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_tecnico_names_to_ids(apps, schema_editor):
    Alistamiento = apps.get_model('api', 'Alistamiento')
    User = apps.get_model('auth', 'User')
    
    fallback_user = User.objects.first()
    if not fallback_user:
        fallback_user = User.objects.create(username='admin', is_staff=True, is_superuser=True)
    
    for alistamiento in Alistamiento.objects.all():
        name = (alistamiento.tecnico_nombre or '').strip()
        if not name:
            alistamiento.tecnico = fallback_user
            alistamiento.save()
            continue
        
        user = User.objects.filter(username__iexact=name).first()
        if not user:
            # Match by first/last name
            for u in User.objects.all():
                full_name = f"{u.first_name} {u.last_name}".strip()
                if full_name.lower() == name.lower() or u.first_name.lower() == name.lower():
                    user = u
                    break
        
        if not user:
            safe_username = name.replace(' ', '_').lower()[:150]
            user, _ = User.objects.get_or_create(username=safe_username, defaults={'first_name': name})
            
        alistamiento.tecnico = user
        alistamiento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_alistamiento_serial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alistamiento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alistamientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_tecnico_names_to_ids, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='alistamiento',
            name='tecnico_nombre',
        ),
        migrations.AlterField(
            model_name='alistamiento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alistamientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
