# Generated by Django 5.2.13 on 2026-07-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_itemhistorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmailBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(help_text='Correo electrónico del destinatario principal', max_length=254)),
                ('asunto', models.CharField(default='Baja de Equipo del Proveedor: {serial}', help_text='Asunto del correo. Puede usar {serial}, {marca}, {modelo}.', max_length=255)),
                ('cuerpo', models.TextField(help_text='Cuerpo del mensaje. Puede usar {serial}, {marca}, {modelo}, {tipo_producto}, {proveedor}, {fecha_baja}.')),
                ('tipo_producto', models.OneToOneField(help_text='Tipo de producto al que aplica esta configuración de correo', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_email_baja', to='api.tipoproducto')),
            ],
            options={
                'verbose_name': 'Configuración Email de Baja',
                'verbose_name_plural': 'Configuraciones Email de Baja',
            },
        ),
    ]
