# Generated by Django 5.2.13 on 2026-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_configuracionemailbaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='es_periferico',
            field=models.BooleanField(default=False, help_text='Indica si este tipo corresponde a un periférico (mouse, teclado, cable, etc.) en lugar de un equipo de cómputo principal'),
        ),
    ]
