# Generated by Django 5.2.13 on 2026-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_es_periferico_to_tipoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionemailbaja',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='configuracionemailbaja',
            name='tipos_producto',
            field=models.ManyToManyField(help_text='Tipos de producto a los que aplica esta configuración de correo', related_name='configuraciones_email_baja', to='api.tipoproducto'),
        ),
    ]
